#!/usr/bin/env bash
#Working on 6-superstitious_numbers
i=1
while [ $i -lt 21 ]; do
	case $i in 4)
		echo "bad luck from China";;
	case $i in 9)
		echo "bad luck from Japan";;
	case $i in 17)
		echo "bad luck from Italy";;
	esac
	echo "$i"
	((i++))
done
