#!/usr/bin/env bash
#Working on 9-to_file_or_not_to_file
if [ -f "school" ]; do
	echo "school file existrsxis"
if [ -s "school" ]; then
	echo "school file is not empty"
elif [ -f "school" ]; then
	echo "school file is empty"
elif [ -f "school" ]; then
	echo "school is a regular file"
else
	echo " school file does not exist"
fi
